### ISSUE TITLE
Registration Problem

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#9] opened 2022-01-20 16:58 UTC
Yesterday one new user couldn't update her Personal Information in the App. After clicking on UPDATE nothing happened.

Today another new user couldn't complete the purchase of the VEDA Tokens. After clicking "Connect Wallet" in the Brokerbot and then clicking on CONNECT in the App he couldn't finish the process in the Brokerbot because the wallet was not connected (the Ethereum address was not displayed). Trying it a second time, and then also on the computer with scanning the QRCode, he again couldn't connect the Brokerbot with the wallet. The App opened without giving a possibility to click CONNECT.

When he then tried to register his address in the Registration Widget again after clicking on "Connect to a Wallet" and selecting the Aktionariat App and clicking on Connect the App opened but without the possibility to click on the blue CONNECT button.

My big questions:
1) Can you see these attempts in your system?
2) What advice do I give the customers?

**Comment by muratogat** [comment] 2022-01-20 19:46
Whenever there is an issue with the app, the first question I ask would be: iOS or Android :)
Second question would be, whether or not the user is using the latest version. Especially we made some significant improvements in recent releases on App-Brokerbot connection.

However, I feel like this one is related to the users network. Especially in corporate office settings, some firewalls are blocking the socket connection required for the App-Brokerbot connection to work. Having the same problem in the Brokerbot and also in the registration widget hints that way. Could the user try the same flow on another network, such as at home, or over 3G?

Meanwhile I'll inspect further.

Unfortunately, I doubt that we have logs of this problem, since it happens during a direct communication between the app and the Brokerbot. Our server has no control or knowledge over that communication.

Thank you for the report.

**Comment by luziusmeisser** [comment] 2022-01-20 20:58
Would it be possible to show an error message when we cannot connect to the walletconnect server?

**Comment by felivix** [comment] 2022-01-20 23:34
> Whenever there is an issue with the app, the first question I ask would be: iOS or Android :) 
_First user: iOS
Second user: Android_

>Second question would be, whether or not the user is using the latest version. Especially we made some significant improvements in recent releases on App-Brokerbot connection.
_Both users downloaded the app yesterday_

> However, I feel like this one is related to the users network. Especially in corporate office settings, some firewalls are blocking the socket connection required for the App-Brokerbot connection to work. Having the same problem in the Brokerbot and also in the registration widget hints that way. Could the user try the same flow on another network, such as at home, or over 3G?
_I will suggest that_

> Meanwhile I'll inspect further.
> Unfortunately, I doubt that we have logs of this problem, since it happens during a direct communication between the app and the Brokerbot. Our server has no control or knowledge over that communication.
_Can you see what they did in the App, like registering and trying to register their Profile - Personal Information? Or registering their E-mail Address?_ 

> Thank you for the report.

**Comment by felivix** [comment] 2022-01-25 17:24
Today, again a person couldn't complete the registration as share holder on her iPhone. We then did it via desktop and QRcode. 
It would indeed be helpful to get error messages when certain steps can't be completed for some reason. 

Is it required that the email registration is confirmed before one can buy tokens or register as shareholder?

**Comment by Nicola8038** [comment] 2022-01-28 06:47
@muratogat Should we open another issue that addresses additional error messages in the app whenever updating personal information didn't work?

**Comment by luziusmeisser** [comment] 2022-01-28 07:13
What also would really be helpful in such cases is a screenshot. It is not entirely clear to me what exactly went wrong, i.e. which button wasn't visible. Trying to reproduce the error, I just experienced a big delay in establishing the connection through walletconnect.

2022-01-28 07:57:23.770 [WebSocketWorker-14] INFO com.aktionariat.bridge.BridgeServer - /127.0.0.1 opened a connection to us
2022-01-28 07:57:23.814 [WebSocketWorker-14] INFO com.aktionariat.bridge.Bridge - /127.0.0.1:57854 wants to know about 52d59c6f-3537-4312-92d3-9bcbe59044f3
**2022-01-28 07:57:31.758 [WebSocketWorker-14] INFO com.aktionariat.bridge.Bridge - Received Message of size 1437 about 52f88f12...**
2022-01-28 07:57:36.680 [WebSocketWorker-15] INFO com.aktionariat.bridge.BridgeServer - /127.0.0.1 opened a connection to us
2022-01-28 07:57:39.906 [main] INFO com.aktionariat.bridge.BridgeServer - Currently, there are 5 bridges.
2022-01-28 07:57:39.906 [main] INFO com.aktionariat.bridge.BridgeServer - Purging inactive connections...
2022-01-28 07:57:39.906 [main] INFO com.aktionariat.bridge.BridgeServer - ... purge of 0 completed in 0ms.
2022-01-28 07:58:23.862 [WebSocketWorker-16] INFO com.aktionariat.bridge.BridgeServer - /127.0.0.1 opened a connection to us
2022-01-28 07:58:23.919 [WebSocketSelector-26] INFO com.aktionariat.bridge.BridgeServer - /127.0.0.1:58098 closed the connection, status 1000
2022-01-28 07:58:39.096 [WebSocketSelector-26] INFO com.aktionariat.bridge.BridgeServer - /127.0.0.1:57860 closed the connection, status 1006
2022-01-28 07:58:43.470 [WebSocketSelector-26] INFO com.aktionariat.bridge.BridgeServer - /127.0.0.1:57854 closed the connection, status 1001
2022-01-28 07:58:44.728 [WebSocketWorker-17] INFO com.aktionariat.bridge.BridgeServer - /127.0.0.1 opened a connection to us
2022-01-28 07:58:44.745 [WebSocketWorker-17] INFO com.aktionariat.bridge.Bridge - /127.0.0.1:58112 wants to know about 47691475-e2ac-423e-b570-e89da0595319
2022-01-28 07:58:54.624 [WebSocketWorker-17] INFO com.aktionariat.bridge.Bridge - Received Message of size 1437 about 1b20a35e...
2022-01-28 07:59:00.830 [WebSocketWorker-18] INFO com.aktionariat.bridge.BridgeServer - /127.0.0.1 opened a connection to us
**2022-01-28 07:59:00.847 [WebSocketWorker-18] INFO com.aktionariat.bridge.Bridge - /127.0.0.1:58340 wants to know about 52f88f12-8ebc-422b-8ecc-7aeda06e2c16**
2022-01-28 07:59:00.847 [WebSocketWorker-18] INFO com.aktionariat.bridge.Bridge - Deliviering Message of size 1437 about 52f88f12... to /127.0.0.1:58340
2022-01-28 07:59:00.859 [WebSocketWorker-18] INFO com.aktionariat.bridge.Bridge - /127.0.0.1:58340 wants to know about 0f40c96f-b9f6-4227-93d4-ce387b7a8c26
2022-01-28 07:59:04.299 [WebSocketSelector-26] INFO com.aktionariat.bridge.BridgeServer - /127.0.0.1:58340 closed the connection, status 1006
2022-01-28 07:59:11.718 [WebSocketWorker-19] INFO com.aktionariat.bridge.BridgeServer - /127.0.0.1 opened a connection to us

@muratogat looking at the server logs, it looks like the app only connected to the server after a delay of 90 seconds! I did the following:

1. At 07:57:31, I initiated a walletconnect session with our registration widget on https://www.aktionariat.com/investor-relations
2. Within seconds, I scanned the QR code with the app. The app vibrated (so it could scan the code) but then, nothing happened.
3. At 07:58:44.728, I reloaded the page, initiated a new connection
4. At 07:59:00, I opened the app again to scan the QR code, and now the "accept connection" overlay popped up before I could scan anything. If you look at the server log, it looks like the app (iOS, latest) was unable to connect to our bridge server (or did not even try to) until a opened it for the second time.

Would it be possible to show an error on failed connection attempts or to show more user feedback? Is there a log file in the app that we could use to see if the app attempted to connect to the bridge server and if yes, if that resulted in a connection error?

**Comment by muratogat** [comment] 2022-02-21 10:41
I have added an error dialog to the iOS app that shows up when the socket connection can't be established.
However it doesn't cover the case when the app is able to connect to the bridge, but somehow the desktop couldn't, so the communication doesn't start.
Also cases when there are no errors but just a slow connection (or bridge, especially with other dapps) does not fail the socket and doesn't create an error.
What we could do is to show a progress dialog, set up a manual timer and terminate the session by force if, for example, 10s have passed and no communication has been received. 
On the desktop it is a bit more difficult, because
- WC library doesn't have an error callback for starting the session
- Again a manual timer workaround could be used, but here the app can scan the QR much later than it is displayed. So there is a trade-off between force closing a socket while users were fetching their phone or even downloading the app, vs. just waiting for a connection that was actually stuck behind a firewall.

**Comment by Nicola8038** [comment] 2022-02-21 17:50
As I understand Felix, these problems only occurred when using the App, so
no connection to the registration widget.

--

Nicola Plain

CEO (ad interim)





Aktionariat AG

CHE-453.438.437

Mobile: +41 78 614 83 47

Email: ***@***.***

Web: https://aktionariat.com <http://aktionariat.com>



<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lw3rh45LM6yW1Lvd7b3T1MdDW49M7Pd1Gy6MB0&si=8000000020887941&pi=8fb68e08-2b91-49b4-8f1b-03cae54ddcc0>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fQ47l4fGCmnW3Fbt5S3zcKScF43TBFPWrCS1&si=8000000020887941&pi=8fb68e08-2b91-49b4-8f1b-03cae54ddcc0>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-4rCvX6W4hCVj23Fbt5SW3F7xMK41RjQSW36dwWw363mD8W3VWt0F4pmP_4W4fxxF_3C36GB0&si=8000000020887941&pi=8fb68e08-2b91-49b4-8f1b-03cae54ddcc0>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fdJS31LdWZ2W3T1MdD49M7Pd0&si=8000000020887941&pi=8fb68e08-2b91-49b4-8f1b-03cae54ddcc0>


*Aktionariat AG is a company founded by Murat Ögat & Luzius Meisser, a
Swiss Blockchain and Crypto Currency Pioneer. *

*Interested in blockchain? This article could be interesting for you: *Eine
Chance für den Finanzplatz | NZZ
<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-41_40qW3F7smG3K53ntW41S2r143TbcQW41Yx_n3JFWPWW43P1h_3QZmG8W1GzPSM3JF3YjW3zdYNr1GBdn5W49h9zp41n_LcW41PG6b45RjbMW4t3zhP1J7CLKW22WLHc49Kv7ZW3F6hB74fN0QQ0&si=8000000020887941&pi=8fb68e08-2b91-49b4-8f1b-03cae54ddcc0>

**Comment by felivix** [comment] 2022-02-21 20:06
@Nicola8038 , actually, it was a communication issue between the widget and the app, not an issue of the app itself. That is why you suggested to try it on 5G because you felt it could be a firewall issue on the WLAN.

**Comment by Nicola8038** [comment] 2022-02-22 06:39
Mea culpa

--

Nicola Plain

CEO (ad interim)





Aktionariat AG

CHE-453.438.437

Mobile: +41 78 614 83 47

Email: ***@***.***

Web: https://aktionariat.com <http://aktionariat.com>



<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lw3rh45LM6yW1Lvd7b3T1MdDW49M7Pd1Gy6MB0&si=8000000020887941&pi=b2955afb-b595-4f48-9a8b-99e33b3f0327>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fQ47l4fGCmnW3Fbt5S3zcKScF43TBFPWrCS1&si=8000000020887941&pi=b2955afb-b595-4f48-9a8b-99e33b3f0327>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-4rCvX6W4hCVj23Fbt5SW3F7xMK41RjQSW36dwWw363mD8W3VWt0F4pmP_4W4fxxF_3C36GB0&si=8000000020887941&pi=b2955afb-b595-4f48-9a8b-99e33b3f0327>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fdJS31LdWZ2W3T1MdD49M7Pd0&si=8000000020887941&pi=b2955afb-b595-4f48-9a8b-99e33b3f0327>


*Aktionariat AG is a company founded by Murat Ögat & Luzius Meisser, a
Swiss Blockchain and Crypto Currency Pioneer. *

*Interested in blockchain? This article could be interesting for you: *Eine
Chance für den Finanzplatz | NZZ
<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-41_40qW3F7smG3K53ntW41S2r143TbcQW41Yx_n3JFWPWW43P1h_3QZmG8W1GzPSM3JF3YjW3zdYNr1GBdn5W49h9zp41n_LcW41PG6b45RjbMW4t3zhP1J7CLKW22WLHc49Kv7ZW3F6hB74fN0QQ0&si=8000000020887941&pi=b2955afb-b595-4f48-9a8b-99e33b3f0327>

**Comment by luziusmeisser** [comment] 2022-02-22 09:17
not sure if it helps, but what I see sometimes is that I can't connect the app to the brokerbot, even when trying repeatedly. what helps in such cases is to shutdown and restart the app. if the app is freshly started, it usually works.

(this was before the latest update)

**Comment by Nicola8038** [comment] 2022-03-23 16:55
Any news on this issue?

**Comment by muratogat** [comment] 2022-03-23 22:11
We are working on a new version of the Brokerbot, which will have the registration process integrated. This could improve cases where both the Brokerbot and the registration widget are on the same page and their connection might interfere.
We are also making improvements to the registration widget, because it will still be available for users who acquire shares by other means.
That being said, the main reason I can't solve the issue for good is that I'm not able to reliably reproduce it. There are 1 maybe 2 occasions per month where I encounter a problem that gets solved by refreshing the page or the app. And rest assured I am using both the registration widget and the Brokerbot daily.
I'll let you know when we have some updates.

**Comment by felivix** [comment] 2022-05-24 11:38
> We are working on a new version of the Brokerbot, which will have the registration process integrated.

Any updates?

**Comment by Nicola8038** [comment] 2022-10-11 09:00
Thanks for the update.

--

Nicola Plain

CEO (ad interim)





Aktionariat AG

CHE-453.438.437

Mobile: +41 78 614 83 47

Email: ***@***.***

Web: https://aktionariat.com <http://aktionariat.com>



<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lw3rh45LM6yW1Lvd7b3T1MdDW49M7Pd1Gy6MB0&si=8000000020887941&pi=2da0afce-3901-4fc2-dd6e-fdc77df20915>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fQ47l4fGCmnW3Fbt5S3zcKScF43TBFPWrCS1&si=8000000020887941&pi=2da0afce-3901-4fc2-dd6e-fdc77df20915>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-4rCvX6W4hCVj23Fbt5SW3F7xMK41RjQSW36dwWw363mD8W3VWt0F4pmP_4W4fxxF_3C36GB0&si=8000000020887941&pi=2da0afce-3901-4fc2-dd6e-fdc77df20915>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fdJS31LdWZ2W3T1MdD49M7Pd0&si=8000000020887941&pi=2da0afce-3901-4fc2-dd6e-fdc77df20915>


*Aktionariat AG is a company founded by Murat Ögat & Luzius Meisser, a
Swiss Blockchain and Crypto Currency Pioneer. *

*Interested in blockchain? This article could be interesting for you: *Eine
Chance für den Finanzplatz | NZZ
<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-41_40qW3F7smG3K53ntW41S2r143TbcQW41Yx_n3JFWPWW43P1h_3QZmG8W1GzPSM3JF3YjW3zdYNr1GBdn5W49h9zp41n_LcW41PG6b45RjbMW4t3zhP1J7CLKW22WLHc49Kv7ZW3F6hB74fN0QQ0&si=8000000020887941&pi=2da0afce-3901-4fc2-dd6e-fdc77df20915>

**Comment by KostasZav** [comment] 2022-10-11 09:38
Since we are now using the new brokerbot V3 with the integrated registration process, I don't see this as a major issue. In any case, the only ones who will need to go through the registration widget and not the new brokerbot are the token holders who got their tokens in the secondary market and want to enjoy their shareholder rights - which to my knowledge is not a very common scenario.

In any case, we can have a deeper look into this issue in case it's needed.

@felivix if there is no problem for you, I will close this issue.

**Comment by felivix** [comment] 2022-10-11 22:26
Thank you!

**Closed** 2022-10-11 22:26 UTC
Labels: bug
